name: Bug Report
labels: [ "bug" ]
description: Submit a bug report
body:
    -   type: textarea
        id: description
        attributes:
            label: Bug Description
            description: Provide a clear and concise description of the bug.
        validations:
            required: true

    -   type: textarea
        id: steps
        attributes:
            label: Steps to Reproduce
            description: List the steps to reproduce the bug.
            value: |
                1. 
                2. 
        validations:
            required: true

    -   type: textarea
        id: expected
        attributes:
            label: Expected Behavior
            description: What did you expect to happen?

    -   type: textarea
        id: env-info
        attributes:
            label: Environment Information
            description: OS info, .NET info, AutoLaunch info, etc.
            placeholder: |
                - OS: Ubuntu 22.04
                - .NET: .NET 8.0.0
                - AutoLaunch: 1.0.0
        validations:
            required: true

    -   type: textarea
        id: additional
        attributes:
            label: Additional Information
            description: Paste screenshots, logs, or error messages here if available.
            placeholder: You can drag images or paste error logs here.
