name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            -   name: Release
                uses: softprops/action-gh-release@v2
                with:
                    prerelease: ${{ contains(github.ref_name, 'preview') }}
                    body: |
                        ## Release Notes
                        
                        ## 发布说明